## Dados para o Painel Semanal 
Script para juntar as informações do primeiro painel semanal do mês.

Criado por : Victor Goncalves
04/01/2023

----
Pegar os dados do CLOSED
> FECHADO  - 1 Mes para tras 
> MES ATUAL ANO ANTERIOR 
> MÊS/ ANO ANTERIOR 
> PROJEÇÃO M1 - 1 Mes para frente 

> COTA - Pegar no IBP;   ???
> META - Pegar no Excel;  ???

> CANAL DIRETO - Somente para MDA.
> LOJA ELUX - Não tem Proj M1
            - Meta é igual a Cota

> CATEG - ADEGA,BEBEDOURO,CERVEJEIRA,FORNO DE BANCADA,FRONT LOAD,SECADORA
        - Utilizar a COTA como META.

#### TABELAS
selloutmensal_trade - Mensal e Previa
selloutsemanal_trade - Semanal

### PARAMETROS DEFINIDOS

In [1]:
import pyodbc
import pandas as pd
from datetime import datetime

In [5]:
server = 'elxa3sql-sobrbiservices-dev-001.database.windows.net' 
database = 'SOBR-BIServices' 
username = 'sobrbiservices' 
password = 'b!brSql01' 

#connection string
conexao = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};\
    SERVER='+server+'; DATABASE='+database+';UID='+username+';PWD='+ password)

conn = conexao.cursor()

# #traz a lista do schema de cada coluna
#columns = [column[0] for column in conn.description]

In [9]:
# SETAR O MES ATUAL, PARA TERMOS O PARAMETRO EM CADA QUERY
data_ref = '2023/01/01'

### MONTANDO OS DATAFRAMES PARA CADA REFERENCIA

In [10]:
## FECHADO
q_fechado = f"""
DECLARE @data_ref DATE;
SET @data_ref = '{data_ref}'
SELECT * FROM selloutmensal_trade WHERE DATA = DATEADD(month,-1,@data_ref) """

result_fechado = conn.execute(q_fechado).fetchall()
# conn.description traz a lista do schema de cada coluna
columns = [column[0] for column in conn.description]

df_fechado = pd.DataFrame.from_records(result_fechado, columns= columns)

df_fechado['STATUS'] = 'FECHADO'
df_fechado.head()

,DATA,BANDEIRA,REGIONAL,MODELO,CATEGORIA,SUBCATEGORIA,MARCA,SELLOUT,ESTOQUE,MDA_SDA,UPLOADED,UPLOAD_METHOD,STATUS
0,2022-12-01,VIA VAREJO,VIA VAREJO,A10N1,ASPIRADOR,ÁGUA E PÓ,ELECTROLUX,71,749,SDA,2023-01-09 13:04:58.053,MANUAL,FECHADO
1,2022-12-01,VIA VAREJO,VIA VAREJO,AQP20,ASPIRADOR,ÁGUA E PÓ,ELECTROLUX,1062,3750,SDA,2023-01-09 13:04:58.053,MANUAL,FECHADO
2,2022-12-01,VIA VAREJO,VIA VAREJO,AWD01,ASPIRADOR,ÁGUA E PÓ,ELECTROLUX,2152,5524,SDA,2023-01-09 13:04:58.053,MANUAL,FECHADO
3,2022-12-01,VIA VAREJO,VIA VAREJO,BC21B,BEBEDOURO ÁGUA,COMPRESSOR,ELECTROLUX,14,212,SDA,2023-01-09 13:04:58.053,MANUAL,FECHADO
4,2022-12-01,VIA VAREJO,VIA VAREJO,BE11B,BEBEDOURO ÁGUA,ELETRONICO,ELECTROLUX,83,895,SDA,2023-01-09 13:04:58.053,MANUAL,FECHADO

In [23]:
df_fechado[df_fechado['BANDEIRA'] == 'MAGAZINE LUIZA']

,DATA,BANDEIRA,REGIONAL,MODELO,CATEGORIA,SUBCATEGORIA,MARCA,SELLOUT,ESTOQUE,MDA_SDA,UPLOADED,UPLOAD_METHOD,STATUS
3064,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,50SBC,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,"0,57",3,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3065,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,52ERS,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,,1,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3066,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,52EXR,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,"12,54",28,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3067,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,52GS,FOGÃO,4Q-SINGLE-GLASS,ELECTROLUX,"0,57",1,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3068,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,52LBR,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,,7,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3465,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,VI12F,AR CONDICIONADO,SPLIT 12.000 BTUS,ELECTROLUX,"3,42",,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3466,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,VI12R,AR CONDICIONADO,SPLIT 12.000 BTUS,ELECTROLUX,,20,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3467,2022-12-01,MAGAZINE LUIZA,REGIONAIS,WD20C,BEBEDOURO ÁGUA,COMPRESSOR,ELECTROLUX,"0,57",3,SDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3468,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,WSF24,ADEGA,20 A 29 GARRAFAS,ELECTROLUX,"5,13",8,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO
3469,2022-12-01,MAGAZINE LUIZA,MAGAZINE LUIZA,WSF34,ADEGA,30 A 39 GARRAFAS,ELECTROLUX,"14,82",8,MDA,2023-01-06 18:01:50.477,MANUAL,FECHADO

In [11]:
## MES ATUAL ANO ANTERIOR

q_mes_atual_ano_anterior = f"""
DECLARE @data_ref DATE;
SET @data_ref = '{data_ref}'
SELECT * FROM selloutmensal_trade
WHERE DATA = DATEADD(year,-1,@data_ref) """

result_mes_atual_ano_anterior = conn.execute(q_mes_atual_ano_anterior).fetchall()
df_mes_atual_ano_anterior = pd.DataFrame.from_records(result_mes_atual_ano_anterior, columns= columns)
df_mes_atual_ano_anterior['STATUS'] = 'MÊS ATUAL ANO ANTERIOR'
df_mes_atual_ano_anterior.head()

,DATA,BANDEIRA,REGIONAL,MODELO,CATEGORIA,SUBCATEGORIA,MARCA,SELLOUT,ESTOQUE,MDA_SDA,UPLOADED,UPLOAD_METHOD,STATUS
0,2022-01-01,B2W,B2W,GST10,FERRO,FERRO,ELECTROLUX,25,85,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS ATUAL ANO ANTERIOR
1,2022-01-01,B2W,B2W,GT30N,ASPIRADOR,ÁGUA E PÓ,ELECTROLUX,604,939,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS ATUAL ANO ANTERIOR
2,2022-01-01,B2W,B2W,IBM10,MIXER,MIXER,ELECTROLUX,0,112,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS ATUAL ANO ANTERIOR
3,2022-01-01,B2W,B2W,IBP50,MIXER,MIXER,ELECTROLUX,3,29,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS ATUAL ANO ANTERIOR
4,2022-01-01,B2W,B2W,LIT31,ASPIRADOR,SEM SACO PARA PÓ,ELECTROLUX,12,10,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS ATUAL ANO ANTERIOR

In [12]:
## MES/ANO ANTERIOR
# dataa = datetime.strptime('2022/10/01','%Y/%m/%d').date()

q_mes_ano_anterior = f"""
DECLARE @data_ref DATE;
SET @data_ref = '{data_ref}'
SELECT * FROM selloutmensal_trade
WHERE DATA = DATEADD(month,-1,DATEADD(year,-1,@data_ref)) """

df_mes_ano_anterior = pd.read_sql(q_mes_ano_anterior, conexao)

df_mes_ano_anterior['STATUS'] = 'MÊS/ANO  ANTERIOR'
df_mes_ano_anterior.head()

c:\Users\goncavic01\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,DATA,BANDEIRA,REGIONAL,MODELO,CATEGORIA,SUBCATEGORIA,MARCA,SELLOUT,ESTOQUE,MDA_SDA,UPLOADED,UPLOAD_METHOD,STATUS
0,2021-12-01,LOJA ELECTROLUX,VENDA DIRETA,PE12A,PURIFICADOR DE ÁGUA,ELETRONICO,ELECTROLUX,86,,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS/ANO ANTERIOR
1,2021-12-01,LOJA ELECTROLUX,VENDA DIRETA,PE12B,PURIFICADOR DE ÁGUA,ELETRONICO,ELECTROLUX,476,,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS/ANO ANTERIOR
2,2021-12-01,LOJA ELECTROLUX,VENDA DIRETA,PE12G,PURIFICADOR DE ÁGUA,ELETRONICO,ELECTROLUX,919,,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS/ANO ANTERIOR
3,2021-12-01,LOJA ELECTROLUX,VENDA DIRETA,PE12V,PURIFICADOR DE ÁGUA,ELETRONICO,ELECTROLUX,29,,SDA,2022-12-28 20:44:55.797,MANUAL,MÊS/ANO ANTERIOR
4,2021-12-01,LOJA ELECTROLUX,VENDA DIRETA,QI09F,AR CONDICIONADO,SPLIT 9.000 BTUS,ELECTROLUX,44,,MDA,2022-12-28 20:44:55.797,MANUAL,MÊS/ANO ANTERIOR

In [13]:
## PROJEÇÃO M1

q_projecao_m1 = f"""
DECLARE @data_ref DATE;
SET @data_ref = '{data_ref}'
SELECT * FROM selloutmensal_trade
WHERE DATA = DATEADD(month,1,@data_ref)"""

df_projecao_m1 = pd.read_sql(q_projecao_m1, conexao)

df_projecao_m1['STATUS'] = 'PROJEÇÃO M1'
df_projecao_m1.head()

c:\Users\goncavic01\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,DATA,BANDEIRA,REGIONAL,MODELO,CATEGORIA,SUBCATEGORIA,MARCA,SELLOUT,ESTOQUE,MDA_SDA,UPLOADED,UPLOAD_METHOD,STATUS
0,2023-02-01,CARREFOUR,HIPERMERCADOS,SON10,ASPIRADOR,COM SACO PARA PÓ,ELECTROLUX,619,,SDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO M1
1,2023-02-01,CARREFOUR,HIPERMERCADOS,STK10,ASPIRADOR,VERTICAL COM FIO,ELECTROLUX,0,,SDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO M1
2,2023-02-01,CARREFOUR,HIPERMERCADOS,STK12,ASPIRADOR,VERTICAL COM FIO,ELECTROLUX,805,,SDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO M1
3,2023-02-01,CARREFOUR,HIPERMERCADOS,STK13,ASPIRADOR,VERTICAL COM FIO,ELECTROLUX,1,,SDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO M1
4,2023-02-01,CARREFOUR,HIPERMERCADOS,STK14,ASPIRADOR,VERTICAL COM FIO,ELECTROLUX,0,,SDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO M1

In [14]:
#PROJEÇÃO 6M - É A PROJEÇÃO DO MÊS PASSADO NA PREVIA

## PROJEÇÃO M1

q_projecao_6m = f"""
DECLARE @data_ref DATE;
SET @data_ref = '{data_ref}'
SELECT * FROM selloutmensal_trade
WHERE DATA = @data_ref"""

df_projecao_6m = pd.read_sql(q_projecao_6m, conexao)

df_projecao_6m['STATUS'] = 'PROJEÇÃO 6M'
df_projecao_6m.head()

c:\Users\goncavic01\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,DATA,BANDEIRA,REGIONAL,MODELO,CATEGORIA,SUBCATEGORIA,MARCA,SELLOUT,ESTOQUE,MDA_SDA,UPLOADED,UPLOAD_METHOD,STATUS
0,2023-01-01,NOVO MUNDO,C.OESTE,52LBU,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,15,,MDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO 6M
1,2023-01-01,NOVO MUNDO,C.OESTE,52LPV,FOGÃO,4Q-SINGLE-GLASS,ELECTROLUX,31,,MDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO 6M
2,2023-01-01,NOVO MUNDO,C.OESTE,52LXS,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,2,,MDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO 6M
3,2023-01-01,NOVO MUNDO,C.OESTE,52SXL,FOGÃO,4Q-SINGLE-INOX,ELECTROLUX,1,,MDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO 6M
4,2023-01-01,NOVO MUNDO,C.OESTE,76DBA,FOGÃO,DUPLO FORNO,ELECTROLUX,3,,MDA,2022-12-28 20:44:55.797,MANUAL,PROJEÇÃO 6M

In [38]:
#df_projecao_6m.to_excel('proj_6M.xlsx')

#### JUNTANDO OS DATA FRAMES

In [24]:
df1 = pd.concat([df_fechado,df_mes_atual_ano_anterior,df_mes_ano_anterior,df_projecao_m1,df_projecao_6m])
len(df1)
#df1.head()

33773

In [25]:
# UPPER EM TODAS AS COLUNAS
# df1.dtypes
df1['BANDEIRA'] = df1['BANDEIRA'].str.upper()
df1['REGIONAL'] = df1['REGIONAL'].str.upper()
df1['MODELO'] = df1['MODELO'].str.upper()
df1['CATEGORIA'] = df1['CATEGORIA'].str.upper()
df1['SUBCATEGORIA'] = df1['SUBCATEGORIA'].str.upper()
df1['MARCA'] = df1['MARCA'].str.upper()

# #TRANSFORMA EM NUMERIC - Ta dando erro!!!!
# df1['ESTOQUE'] = pd.to_numeric(df1['ESTOQUE'], errors='coerce')
# df1['SELLOUT'] = pd.to_numeric(df1['SELLOUT'], errors='coerce')

### DEFININDO OS CLIENTES DO SEMANAL

In [26]:
rede_semanal = ['Allied','Amazon','Angeloni','B2W','Bemol','Benoit','Big','Camicado','Canal Direto','Carrefour','Carrefour.Com'
,'Casa e Video','Claudino','Colombo','Colombo.com','Comprebel','Condor','Eletro Matheus','Eletrozema','Estrela','Fast Shop','Fast Shop.com'
,'Formosa','Friopeças','G. Barbosa','Gazin','Havan','Império','Infoar','Leroy Merlin','Loja Electrolux','Magazine Liliani'
,'Magazine Luiza','Magazine Luiza.com','Market Place','Martinello','Martins','Master','Mercado Livre','Millena','Nosso Lar'
,'Novo Mundo','Novo Mundo.com','Pernambucanas','Quero-Quero','Ramsons','Rcell','Sams Club','Simonetti','Sipolatti','Tv Lar'
,'Via Varejo','Via Varejo.Com','Zenir']

In [27]:
# TRANSFORMANDO EM UPPER as redes
rede_semanal_u = []
for x in rede_semanal:
    rede_semanal_u.append(x.upper())

In [19]:
rede_semanal_u

['ALLIED',
 'AMAZON',
 'ANGELONI',
 'B2W',
 'BEMOL',
 'BENOIT',
 'BIG',
 'CAMICADO',
 'CANAL DIRETO',
 'CARREFOUR',
 'CARREFOUR.COM',
 'CASA E VIDEO',
 'CLAUDINO',
 'COLOMBO',
 'COLOMBO.COM',
 'COMPREBEL',
 'CONDOR',
 'ELETRO MATHEUS',
 'ELETROZEMA',
 'ESTRELA',
 'FAST SHOP',
 'FAST SHOP.COM',
 'FORMOSA',
 'FRIOPEÇAS',
 'G. BARBOSA',
 'GAZIN',
 'HAVAN',
 'IMPÉRIO',
 'INFOAR',
 'LEROY MERLIN',
 'LOJA ELECTROLUX',
 'MAGAZINE LILIANI',
 'MAGAZINE LUIZA',
 'MAGAZINE LUIZA.COM',
 'MARKET PLACE',
 'MARTINELLO',
 'MARTINS',
 'MASTER',
 'MERCADO LIVRE',
 'MILLENA',
 'NOSSO LAR',
 'NOVO MUNDO',
 'NOVO MUNDO.COM',
 'PERNAMBUCANAS',
 'QUERO-QUERO',
 'RAMSONS',
 'RCELL',
 'SAMS CLUB',
 'SIMONETTI',
 'SIPOLATTI',
 'TV LAR',
 'VIA VAREJO',
 'VIA VAREJO.COM',
 'ZENIR']

### SOMENTE CLIENTES DO SEMANAL

In [28]:
# DATAFRAME PARA OS CLIENTES DO SEMANAL
df2 = df1[df1['BANDEIRA'].isin(rede_semanal_u)]

len(df2)

30474

In [21]:
#CONVERTER A COLUNA SELL OUT EM NUMERIC

#df2['SELLOUT'] = df2['SELLOUT'].apply(lambda x: float(x.split()[0].replace(',', '.')))
# df2['ESTOQUE'] = df2['ESTOQUE'].apply(lambda y: float(y.split()[0].replace(',', '.')))
df2['ESTOQUE'] = pd.to_numeric(df2['ESTOQUE'], errors='coerce')
df2['SELLOUT'] = pd.to_numeric(df2['SELLOUT'], errors='coerce')

C:\Users\goncavic01\AppData\Local\Temp\ipykernel_23876\766179256.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['ESTOQUE'] = pd.to_numeric(df2['ESTOQUE'], errors='coerce')
C:\Users\goncavic01\AppData\Local\Temp\ipykernel_23876\766179256.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['SELLOUT'] = pd.to_numeric(df2['SELLOUT'], errors='coerce')

In [24]:
# TA DANDO ERRO DE NUMERAL (VIRGULA)
# df2_g = df2.groupby(['BANDEIRA','DATA'])['SELLOUT'].sum().apply(lambda x: x[x['BANDEIRA']== 'MAGAZINE LUIZA']])
#df2.groupby(['BANDEIRA','DATA']).apply(lambda x: x[x['BANDEIRA']== 'MAGAZINE LUIZA'])['SELLOUT'].sum()
# df2_g[df2_g['BANDEIRA'] == 'MAGAZINE LUIZA']

# ,'MAGAZINE LUIZA.COM']]

253773.0

In [29]:
df2.to_excel('df2.xlsx')